quarkus.http.port=8899
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=app_barberia_instancia_user
quarkus.datasource.password=lPsGWNtXkXdT9BFyZjXMf354qQKpcXXP
quarkus.datasource.jdbc.url=jdbc:postgresql://dpg-d7snkebbc2fs73cu0lv0-a.oregon-postgres.render.com:5432/app_barberia_instancia?sslmode=require
quarkus.hibernate-orm.database.generation=drop-and-create