# Aplicación
quarkus.application.name=Aureum
quarkus.application.version=1.0-SNAPSHOT

# HTTP
quarkus.http.port=8899
quarkus.http.host=localhost
quarkus.http.root-path=api
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization,X-Requested-With

# Base de datos
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=app_barberia_instancia_user
quarkus.datasource.password=lPsGWNtXkXdT9BFyZjXMf354qQKpcXXP
quarkus.datasource.jdbc.url=jdbc:postgresql://dpg-d7snkebbc2fs73cu0lv0-a.oregon-postgres.render.com:5432/app_barberia_instancia?sslmode=require

# Hibernate ORM
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Configuración de Logs
quarkus.log.level=INFO

# Logs de Consola
quarkus.log.console.enabled=true
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n
quarkus.log.console.dark-launch=true

# Logs de Archivo
quarkus.log.file.enabled=true
quarkus.log.file.path=logs/barbero.log
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n
quarkus.log.file.rotation.max-file-size=5M
quarkus.log.file.rotation.max-backup-index=5
quarkus.log.file.rotation.file-suffix=yyyy-MM-dd